repos:
  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.4.1'
    hooks:
      - id: prettier
        types_or: [css, javascript]
  - repo: https://github.com/chrissantamaria/mirrors-js-beautify
    rev: 'v1.14.0'
    hooks:
      - id: js-beautify
        types_or: [html]
