# Generated by Django 3.2.7 on 2021-10-30 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="numbath",
            new_name="num_bathrooms",
        ),
        migrations.RenameField(
            model_name="listing",
            old_name="numrooms",
            new_name="num_rooms",
        ),
    ]
