# Generated by Django 3.2.7 on 2021-10-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20211030_2058"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="listing",
            name="longitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="listing",
            name="num_bathrooms",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="listing",
            name="num_rooms",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="listing",
            name="zipcode",
            field=models.PositiveIntegerField(),
        ),
    ]
