# Generated by Django 3.2.7 on 2021-11-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.ImageField(default=2, upload_to="images/"),
            preserve_default=False,
        ),
    ]
