# Generated by Django 3.2.7 on 2021-11-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
